# Generated by Django 3.0.4 on 2020-03-10 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=40)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('story_type', models.CharField(max_length=30)),
                ('complexity', models.IntegerField()),
                ('estimated_time', models.TimeField()),
                ('cost', models.FloatField()),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='userstory.User')),
                ('last_updated_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stories_updated', to='userstory.User')),
            ],
        ),
    ]
