# Generated by Django 3.0.4 on 2020-03-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_auto_20200312_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_user', to='userstory.User'),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_updated_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_user', to='userstory.User'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
